project:
  type: book

book:
  title: "Crimes"
  subtitle: "Evaluación de Modelos Autocorrelación Espacial"
  author: "FONDECYT"
  date: "8/20/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - marco_teorico.qmd
    - cvm_ppp.qmd
    - cvm_sim.qmd
    - residuos.qmd
    - funciones.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



