project:
  type: book

book:
  title: "Crimes"
  subtitle: "Evaluación de Modelos Autocorrelación Espacial"
  author: "FONDECYT"
  date: "8/20/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - marco_teorico.qmd
    - cvm_ppp.qmd
    - residuos.qmd
    - funciones.qmd
    - references.qmd

bibliography: references.bib


format:
  html:
    theme: cosmo
    html-math-method: katex
    css: style.css

editor: visual
always_allow_html: true


