options(scipen = 999, stringsAsFactors=F, encoding = "UTF-8",max.print=1000000)

#### load libraries
suppressPackageStartupMessages(library(DescTools))
suppressPackageStartupMessages(library(spatialreg))
suppressPackageStartupMessages(library(MASS))
suppressPackageStartupMessages(library(lme4))
suppressPackageStartupMessages(library(doSNOW))
suppressPackageStartupMessages(library(snow))
suppressPackageStartupMessages(library(iterators))
suppressPackageStartupMessages(library(parallel))
suppressPackageStartupMessages(library(doParallel))
suppressPackageStartupMessages(library(foreach))
# suppressPackageStartupMessages(# library(xlsx))
suppressPackageStartupMessages(library(clusterSim))
suppressPackageStartupMessages(library(spdep))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(BAMMtools))
suppressPackageStartupMessages(library(openxlsx))
suppressPackageStartupMessages(library(ggmap))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(leaflet))
suppressPackageStartupMessages(library(raster))
suppressPackageStartupMessages(library(ecespa))
suppressPackageStartupMessages(library(mapview))
